@extends('layouts.app')

@section('title', 'National Executive Committee — FEHSU')
@section('description', 'Meet the National Executive Committees of FEHSU\'s 11 member associations across Uganda\'s environmental health sector.')

@section('content')
<section class="page-hero has-photo">
<div class="hero-photo" style="background-image:url('/images/5.jpeg')"></div>
<div class="hero-overlay"></div>
<div class="wrap">
<span class="eyebrow mono" style="margin-bottom:8px;"><span class="dot"></span>MEMBER DIRECTORY · SINCE 2022</span>
<h1 class="display">National Executive Committee</h1>
<p class="sub">The National Executive Committees of FEHSU's 11 member associations. Pick an association below and tap any photo for a closer look.</p>
</div>
</section>
<section class="sec">
<div class="wrap">
<div class="callout" style="margin-bottom:40px;">
<span class="icon">i</span>
<p>Looking for the current leadership? Visit the <a href="/corporate">Central Executive Committee</a> page to meet this term's officers.</p>
</div>

<div class="assoc-section balanced" id="member-associations">
<div class="assoc-section-head">
<span class="tag mono">MEMBER ASSOCIATIONS</span>
<h2 class="display">Association executives</h2>
<p>FEHSU's 11 member associations, each with its own National Executive Committee. Select an association to open its executive chart, then click any photo to zoom in.</p>
</div>
<div class="assoc-grid" id="assocGrid"><!-- Circular logo buttons are generated by JS from the ASSOCIATIONS array near the bottom of this page --></div>
</div>

</div>
</section>

<!-- Association executive chart modal -->
<div class="chart-modal" id="chartModal" aria-hidden="true">
<div class="chart-modal-backdrop" data-chart-close></div>
<div class="chart-modal-panel" role="dialog" aria-modal="true" aria-labelledby="chartHeaderName">
<button type="button" class="chart-modal-close" data-chart-close aria-label="Close chart">✕</button>
<div class="chart-header">
<div class="chart-header-logo" id="chartHeaderLogo"></div>
<div class="chart-header-text">
<span class="eyebrow-sm" id="chartHeaderShort"></span>
<h3 id="chartHeaderName"></h3>
</div>
</div>
<div class="chart-body">
<div class="chart-president" id="chartPresident"></div>
<div class="chart-officers-grid" id="chartOfficers"></div>
</div>
</div>
</div>

<!-- Zoomed photo lightbox for people inside an association chart -->
<div class="chart-photo-modal" id="chartPhotoModal" aria-hidden="true">
<div class="chart-photo-modal-backdrop" data-chart-photo-close></div>
<div class="chart-photo-modal-panel" role="dialog" aria-modal="true" aria-labelledby="chartPhotoName">
<button type="button" class="chart-photo-modal-close" data-chart-photo-close aria-label="Close">✕</button>
<div class="chart-photo-modal-media">
<button type="button" class="chart-photo-nav prev" id="chartPhotoPrev" aria-label="Previous person">‹</button>
<img id="chartPhotoImg" src="" alt="">
<button type="button" class="chart-photo-nav next" id="chartPhotoNext" aria-label="Next person">›</button>
</div>
<div class="chart-photo-modal-info">
<h3 id="chartPhotoName"></h3>
<p id="chartPhotoPost"></p>
</div>
</div>
</div>

<!-- Tap-to-zoom photo modal (zoom-out effect on this page) -->
<div class="photo-modal zoom-out" id="photoModal" data-effect="zoom-out" aria-hidden="true">
<div class="photo-modal-backdrop" data-close></div>
<div class="photo-modal-panel" role="dialog" aria-modal="true" aria-labelledby="modalName">
<button type="button" class="photo-modal-close" data-close aria-label="Close">✕</button>
<div class="photo-modal-media">
<button type="button" class="photo-modal-nav prev" data-nav="prev" aria-label="Previous person">‹</button>
<img id="modalImg" src="" alt="">
<button type="button" class="photo-modal-nav next" data-nav="next" aria-label="Next person">›</button>
<span class="photo-modal-count" id="modalCount"></span>
</div>
<div class="photo-modal-info">
<h3 id="modalName"></h3>
<p class="role" id="modalRole"></p>
<p class="bio" id="modalBio"></p>
</div>
</div>
</div>
@endsection

@push('scripts')
<script>
(function(){
      // ---------------------------------------------------------------
      // EDIT ME: one entry per member association. Change short/name/logo,
      // and each person's photo, name, post (title) and school.
      // photo: any image path in this folder. logo: association logo image
      // (falls back automatically to circle initials if the file is missing).
      // ---------------------------------------------------------------
      var ASSOCIATIONS = [
        {
          id: "assoc1", short: "FEHSU", name: "Member Association", logo: "PHOTO.jpeg",
          president: { photo: "CEC/demus.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "FEHSU -Makerere University" },
          officers: [
            { photo: "CEC/denise.jpg", name: "Kainomugisha Denis", post: "Minister for External Affairs", school: "FEHSU -Makerere University" },
            { photo: "CEC/Joan.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "UIAHMS-MULAGO" },
            { photo: "CEC/Abdul.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "MSOHESHA" },
            { photo: "CEC/Edgar.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "BEHSA" },
            { photo: "CEC/JONA.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "FEHSU -Makerere University" },
            { photo: "CEC/nampwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "UIAHMSM" },
            { photo: "CEC/Joan.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/assumpita.jpg", name: "Namwanga Maria Assumpta", post: "INTERNAL MINISTER", school: "FEHSU -Makerere University" },

            
          ]
        },
        {
          id: "assoc2", short: "MUEHSA", name: "Member Association ", logo: "MUEHSA.png",
          president: { photo: "CEC/demu.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdu.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edga.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/nampwer.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nicodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc3", short: "MEHSA", name: "Member Association ", logo: "MEHSA.JPG",
          president: { photo: "CEC/demu.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdu.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/nampwer.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc4", short: "MMUPHSA", name: "Member Association ", logo: "PHS.png",
          president: { photo: "CEC/demus.jpg", name: "Agumenawe Nicodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdu.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edga.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/demus.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/ni.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
        {
          id: "assoc5", short: "BWERA", name: "Member Association ", logo: "bwera.jpg",
          president: { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "PRESIDENT", school: "Institution / School" },
          officers: [
            { photo: "CEC/denis.jpg", name: "Kainomugisha Denis", post: "GENERAL SECRETARY", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "FINANCE MINISTER", school: "Institution / School" },
            { photo: "CEC/Abdl.jpg", name: "Alafi Abdul Rahuman", post: "MINISTER FOR EXTERNAL AFFAIRS", school: "Institution / School" },
            { photo: "CEC/Edgr.jpg", name: "Muhindo Edgar", post: "PUBLICITY MINISTER", school: "Institution / School" },
            { photo: "CEC/JON.jpg", name: "Magomu Jonah Cornelinus", post: "PROJECTS MINISTER", school: "Institution / School" },
            { photo: "CEC/namwera.jpg", name: "Nampwera Rebecca", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/nic.jpg", name: "Agumenawe Nichodemus", post: "INTERNAL MINISTER", school: "Institution / School" },
            { photo: "CEC/Joa.jpg", name: "Auma Joan Angel", post: "INTERNAL MINISTER", school: "Institution / School" },
          ]
        },
      ];

      function initials(str){
        return (str||'').replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase();
      }

      // ---- Render the 11 circular logo buttons ----
      var assocGrid = document.getElementById('assocGrid');
      if(assocGrid){
        ASSOCIATIONS.forEach(function(a){
          var btn = document.createElement('button');
          btn.type = 'button';
          btn.className = 'assoc-item';
          btn.setAttribute('data-assoc-id', a.id);
          btn.innerHTML =
            '<span class="assoc-logo-circle">' +
              '<img src="/images/'+a.logo+'" alt="'+a.name+' logo" onerror="this.replaceWith(Object.assign(document.createElement(\'span\'),{className:\'fallback-initials\',textContent:\''+initials(a.short)+'\'}))">' +
            '</span>' +
            '<span class="assoc-full-name">'+a.name+'</span>' +
            '<span class="assoc-shortname-btn">'+a.short+'</span>';
          btn.addEventListener('click', function(){ openChart(a.id); });
          assocGrid.appendChild(btn);
        });
      }

      // ---- Build one chart "card" (used for both the president and officers) ----
      function buildCard(person, isPresident){
        var card = document.createElement('div');
        card.className = 'chart-card';
        card.innerHTML =
          '<div class="post-bar">'+person.post+'</div>' +
          '<div class="photo-wrap"><img src="/images/'+person.photo+'" alt="'+person.name+'"></div>' +
          '<div class="card-text"><h4>'+person.name+'</h4><p>'+person.school+'</p></div>';
        card.querySelector('.photo-wrap').addEventListener('click', function(){
          openChartPhoto(person, isPresident ? 'president' : 'officers');
        });
        return card;
      }

      // ---- Open / close the association chart modal ----
      var chartModal = document.getElementById('chartModal');
      var chartHeaderLogo = document.getElementById('chartHeaderLogo');
      var chartHeaderShort = document.getElementById('chartHeaderShort');
      var chartHeaderName = document.getElementById('chartHeaderName');
      var chartPresidentEl = document.getElementById('chartPresident');
      var chartOfficersEl = document.getElementById('chartOfficers');
      var currentAssoc = null;
      var chartLastFocused = null;

      function openChart(id){
        var a = ASSOCIATIONS.filter(function(x){ return x.id===id; })[0];
        if(!a) return;
        currentAssoc = a;

        chartHeaderLogo.innerHTML = '<img src="/images/'+a.logo+'" alt="'+a.name+' logo" onerror="this.replaceWith(Object.assign(document.createElement(\'span\'),{className:\'fallback-initials\',textContent:\''+initials(a.short)+'\'}))">';
        chartHeaderShort.textContent = a.short + ' · NATIONAL EXECUTIVE COMMITTEE';
        chartHeaderName.textContent = a.name;

        chartPresidentEl.innerHTML = '';
        chartPresidentEl.appendChild(buildCard(a.president, true));

        chartOfficersEl.innerHTML = '';
        a.officers.forEach(function(o){ chartOfficersEl.appendChild(buildCard(o, false)); });

        chartLastFocused = document.activeElement;
        chartModal.classList.add('open');
        chartModal.setAttribute('aria-hidden','false');
        document.body.classList.add('modal-open');
        chartModal.querySelector('.chart-modal-close').focus();
      }
      function closeChart(){
        chartModal.classList.remove('open');
        chartModal.setAttribute('aria-hidden','true');
        document.body.classList.remove('modal-open');
        if(chartLastFocused) chartLastFocused.focus();
      }
      if(chartModal){
        chartModal.querySelectorAll('[data-chart-close]').forEach(function(el){ el.addEventListener('click', closeChart); });
      }

      // ---- Photo zoom lightbox for people inside a chart ----
      var chartPhotoModal = document.getElementById('chartPhotoModal');
      var chartPhotoImg = document.getElementById('chartPhotoImg');
      var chartPhotoName = document.getElementById('chartPhotoName');
      var chartPhotoPost = document.getElementById('chartPhotoPost');
      var chartPhotoPrev = document.getElementById('chartPhotoPrev');
      var chartPhotoNext = document.getElementById('chartPhotoNext');
      var photoGroup = [];
      var photoIndex = 0;
      var photoLastFocused = null;

      function renderChartPhoto(){
        var person = photoGroup[photoIndex];
        if(!person) return;
        chartPhotoImg.src = '/images/' + person.photo;
        chartPhotoImg.alt = person.name;
        chartPhotoName.textContent = person.name;
        chartPhotoPost.textContent = person.post + ' — ' + person.school;
        chartPhotoPrev.disabled = photoGroup.length < 2;
        chartPhotoNext.disabled = photoGroup.length < 2;
      }
      function openChartPhoto(person){
        if(!currentAssoc) return;
        photoGroup = [currentAssoc.president].concat(currentAssoc.officers);
        photoIndex = photoGroup.indexOf(person);
        if(photoIndex < 0) photoIndex = 0;
        photoLastFocused = document.activeElement;
        chartPhotoModal.classList.add('open');
        chartPhotoModal.setAttribute('aria-hidden','false');
        renderChartPhoto();
        chartPhotoModal.querySelector('.chart-photo-modal-close').focus();
      }
      function closeChartPhoto(){
        chartPhotoModal.classList.remove('open');
        chartPhotoModal.setAttribute('aria-hidden','true');
        if(photoLastFocused) photoLastFocused.focus();
      }
      function stepChartPhoto(dir){
        if(photoGroup.length < 2) return;
        photoIndex = (photoIndex + dir + photoGroup.length) % photoGroup.length;
        renderChartPhoto();
      }
      if(chartPhotoModal){
        chartPhotoModal.querySelectorAll('[data-chart-photo-close]').forEach(function(el){ el.addEventListener('click', closeChartPhoto); });
        chartPhotoPrev.addEventListener('click', function(){ stepChartPhoto(-1); });
        chartPhotoNext.addEventListener('click', function(){ stepChartPhoto(1); });
      }

      document.addEventListener('keydown', function(e){
        if(chartPhotoModal && chartPhotoModal.classList.contains('open')){
          if(e.key==='Escape') closeChartPhoto();
          if(e.key==='ArrowLeft') stepChartPhoto(-1);
          if(e.key==='ArrowRight') stepChartPhoto(1);
          return;
        }
        if(chartModal && chartModal.classList.contains('open')){
          if(e.key==='Escape') closeChart();
        }
      });

})();
</script>
@endpush
